.node-job:
  image: node:20
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key: npm
    paths:
      - .npm/

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_MERGE_REQUEST_MERGED

stages:
  - code checks
  - build

lint:
  extends: .node-job
  stage: code checks
  script:
    - npm run lint

build:
  extends: .node-job
  stage: build
  script:
    - npm run build
