version: "3"

services:
  nextjs-prod:
    container_name: nextjs-prod
    build:
      dockerfile: ./docker/dockerfile/Dockerfile.prod
      context: ../
    restart: on-failure
    volumes:
      - /app/node_modules
    expose:
      - "9000"
    networks:
      - demo

  nginx-prod:
    container_name: nginx-prod
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    networks:
      - demo
    depends_on:
      - nextjs-prod

networks:
  demo:
    external: true
