version: "3.8"

services:
  nextjs-dev:
    container_name: nextjs-dev
    build:
      dockerfile: ./docker/dockerfile/Dockerfile.dev
      context: ../
    restart: on-failure
    volumes:
      - ../:/app
      - /app/node_modules
    expose:
      - "3000"
    networks:
      - my-psychologist

  nginx-dev:
    container_name: nginx-dev
    image: nginx:latest
    restart: on-failure
    volumes:
      - ../:/app
      - /app/node_modules
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - my-psychologist
    depends_on:
      - nextjs-dev

networks:
  my-psychologist:
    driver: bridge
