version: "3.8"

services:
  nextjs-prod:
    container_name: nextjs-prod
    build:
      dockerfile: ./docker/dockerfile/Dockerfile.prod
      context: ../
    restart: on-failure
    volumes:
      - /app/node_modules
    expose:
      - "3000"
    networks:
      - my-psychologist

  nginx-prod:
    container_name: nginx-prod
    image: nginx:latest
    restart: on-failure
    volumes:
      - /app/node_modules
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - my-psychologist
    depends_on:
      - nextjs-prod

networks:
  my-psychologist:
    driver: bridge
