services:
  frontend:
    container_name: odeyalo-frontend
    build:
      dockerfile: ./docker/dockerfile/Dockerfile
      context: ../
    restart: on-failure
    volumes:
      - /app/app
    expose:
      - "3000"
    networks:
      - demo
    mac_address: 02:42:ac:18:06:01

  nginx:
    container_name: odeyalo-frontend-nginx
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    networks:
      - demo
    depends_on:
      - frontend
    mac_address: 02:42:ac:18:06:02

networks:
  demo:
    external: true
