version: "3"

services:
  nextjs-prod:
    container_name: nextjs-prod
    build:
      dockerfile: ./docker/dockerfile/Dockerfile.prod
      context: ../
    restart: on-failure
    volumes:
      - /app/node_modules
    expose:
      - "3000"
    networks:
      - demo
    mac_address: 02:42:ac:18:06:01

  nginx-prod:
    container_name: nginx-prod
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    networks:
      - demo
    depends_on:
      - nextjs-prod
    mac_address: 02:42:ac:18:06:02

networks:
  demo:
    external: true
